### PR TITLE
Add .satisfies(predicate, *args), and tests

### PR DESCRIPTION
**Pull request by dpercy**

### CODE REVIEW

**Comment by dpercy** [comment]
Oops, I didn't test `make test3`

**Comment by kislyuk** [comment]
Looks good so far, but why do you take/pass through `*args` but no `**kwargs`?

**Comment by dpercy** [comment]
That case didn't seem as useful, but I guess there's no harm in adding it.

**Comment by kislyuk** [comment]
Thanks, this looks good so far.

**Pull request merged**
